import ApresentationSection from '../src/components/ApresentationSection';
import ProjectsSection from '../src/components/ProjectsSection';
import { HomeMain } from '../src/styles/homepage';
import Head from 'next/head';

const Home = () => {
  return (
    <>
      <Head>
        <title>Breno Rosado</title>
        <meta name="Breno Rosado" content="Generated by create next app" />
        {/* <link rel="icon" href="/spiderman.ico" /> */}
      </Head>
      <HomeMain>
        <ApresentationSection />
        <ProjectsSection />
      </HomeMain>
    </>
  );
};

export default Home;