import ApresentationSection from '../src/components/ApresentationSection';
import ProjectsSection from '../src/components/ProjectsSection';
import { HomeMain } from '../src/styles/homepage';
import Head from 'next/head';
import ContactSection from '../src/components/ContactSection';
import CurriculumSection from '../src/components/CurriculumSection';

const Home = () => {
  return (
    <>
      <Head>
        <title>Breno Rosado</title>
        <meta name="Breno Rosado" content="Generated by create next app" />
        <link rel="icon" href="/logo.ico" />
      </Head>
      <HomeMain>
        <ApresentationSection />
        <ProjectsSection />
        <ContactSection />
        <CurriculumSection />
      </HomeMain>
    </>
  );
};

export default Home;